<script>
$(document).ready(function() {
  $("#owl-books").owlCarousel({
      loop:true,
      margin:10,
      nav:true,
      responsive:{
          0:{
              items:1
          },
          600:{
              items:4
          },
          1000:{
              items:6
          }
      }
  });
});
</script>
<script>
$(document).ready(function() {
  $("#owl-books2").owlCarousel({
      loop:true,
      margin:10,
      nav:true,
      responsive:{
          0:{
              items:1
          },
          600:{
              items:4
          },
          1000:{
              items:6
          }
      }
  });
});
</script>
<script>
$(document).ready(function() {
  $("#owl-books3").owlCarousel({
      loop:true,
      margin:10,
      nav:true,
      responsive:{
          0:{
              items:1
          },
          600:{
              items:4
          },
          1000:{
              items:6
          }
      }
  });
});
</script>
<script>
$(document).ready(function() {
  $("#owl-books4").owlCarousel({
      loop:true,
      margin:10,
      nav:true,
      responsive:{
          0:{
              items:1
          },
          600:{
              items:4
          },
          1000:{
              items:6
          }
      }
  });
});
</script>